### ISSUE TITLE
The error will be open when we create an table storage output

### ISSUE THREAD

**Issue by asatestaccount** [microsoft/vscode-asa#1]
Repro steps:
<Enter steps to reproduce issue>

Action: asa.config.provideCodeLenses
Error type: Error
Error Message: cannot parse propertyName: 'PathPattern' from target json

Version: 0.0.1
OS: win32

**Comment by ms-guizha** [comment]
we have released out latest version and your issue should be fixed.
https://marketplace.visualstudio.com/items?itemName=ms-bigdatatools.vscode-asa

**Comment by authuir** [comment]
Closed as resolved.
