### ISSUE TITLE
[Survery] User feedback

### ISSUE THREAD

**Issue by shijiaxing** [microsoft/vscode-asa#11]
VSCode Version: 1.37.1,
Extension Version: 0.1.2,
OS: Windows

**1. Overall, how would you rate your experience with the Stream Analytics Visual Studio Code Extension? Please rate us from 1 (poor) to 10 (excellent).**
7

**2. What do you like or dislike about the Stream Analytics Visual Studio Code Extension?**
Like: support run job locally
Dislike: don't support to run Javascript UDF in Mac / Linux

**3. What improvements do you suggest for Stream Analytics Visual Studio Code Extension?**
1. Make it consistent between different platform
2. Right click on a asaql file to execute it

**Comment by ms-guizha** [comment]
thanks for your feedbacks. for the improvements :  
1 The engine we are using for ASA JS is only for windows currently,  we will sync with framework team whether is better solution for JS function cross platform. We are planning to support CSharp UDF in the future and this will be more powerful than JS I think.

2 This is really valuable feedback, we will consider supporting it as another entrance for local run.

**Comment by su-jie** [comment]
Hi Jason,

In the latest VS Code extension (0.1.7), we added a context menu for start local run by right clicking on the scrip file. Welcome to try it!

![image](https://user-images.githubusercontent.com/24801534/69218727-46e64d00-0bac-11ea-9325-cdcfcb885ba8.png)

Thanks,
Jie

**Comment by shijiaxing** [comment]
It works well, thanks.
