### ISSUE TITLE
[Survery] User feedback

### ISSUE THREAD

**Issue by xaxdev** [microsoft/vscode-asa#21]
VSCode Version: 1.40.2,
Extension Version: 0.2.0,
OS: Windows

**1. Overall, how would you rate your experience with the Stream Analytics Visual Studio Code Extension? Please rate us from 1 (poor) to 10 (excellent).**

**2. What do you like or dislike about the Stream Analytics Visual Studio Code Extension?**

**3. What improvements do you suggest for Stream Analytics Visual Studio Code Extension?**

**Comment by su-jie** [comment]
Hi xaxdev, do you have feedback for the tools?

**Comment by xaxdev** [comment]
Hi @su-jie.
Thanks for looks at my first-test project.
But now, I must to go back to ERP Develop.

Best Regards/
