### ISSUE TITLE
ASAQL System.TimeStamp() syntax errors with valid query

### ISSUE THREAD

**Issue by daltskin** [microsoft/vscode-asa#4]
Using the sliding window query with System.TimeStamp() as per documentation (https://docs.microsoft.com/en-us/stream-analytics-query/sliding-window-azure-stream-analytics) eg:

`
SELECT DateAdd(minute,-1,System.Timestamp()) AS WinStartTime, System.Timestamp() AS WinEndTime, COUNT(*)
INTO
	PaymentOutput
FROM
	PaymentInput
GROUP By SlidingWindow(minute, 1)
`

Results in syntax errors when submitting to Azure:

[Error]  Syntax errors: 
[Error]  extraneous input '(' expecting ')'. Location: line 1, column 41.
[Error]  mismatched input ')' expecting {',', 'FROM', 'INTO'}. Location: line 1, column 43.
[Error]  mismatched input ')' expecting {'(', 'SELECT'}. Location: line 1, column 79.
[Error]  mismatched input 'AS' expecting {<EOF>, 'GO'}. Location: line 1, column 81.

Removing the brackets from timestamp resolves the problem:

`
SELECT DateAdd(minute,-1,System.Timestamp) AS WinStartTime, System.Timestamp AS WinEndTime, COUNT(*)
INTO
	PaymentOutput
FROM
	PaymentInput
GROUP By SlidingWindow(minute, 1)
`

**Comment by ms-guizha** [comment]
thanks for your feedback, we will fix it as soon as possible

**Comment by ms-guizha** [comment]
We have released a new bits for VS code and you issue mentioned has been fixed.

**Comment by authuir** [comment]
Closed as resolved.
