### ISSUE TITLE
Selecting local file path freezes window manager (Ubuntu)

### ISSUE THREAD

**Issue by aressler38** [microsoft/vscode-asa#53]
Issue Type: <b>Bug</b>

In the Inputs/input.json file, if you setup a local data input and click "Select local file path" just above the "FilePath" property, then the window manager freezes. I've tried Genome and KDE Plasma destops. Both freeze. 

![image](https://user-images.githubusercontent.com/2053500/124798022-ea6ea780-df20-11eb-9b69-3a392d63ece0.png)

Extension version: 0.8.3
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-59-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 4188)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 0, 0|
|Memory (System)|62.44GB (58.83GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id dac47f5e-820c-45f6-baf6-7d690c95eedc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30322571
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
bridge0702cf:30334634

```

</details>

**Comment by yicw16322** [comment]
Hi aressler38, thank you for your feedback, we are checking the issue you reported now, hope we could get back to you soon

**Comment by yicw16322** [comment]
Hi @aressler38, we are working on investigating, could you please try to upgrade your extension to newest version and have a try?

**Comment by aressler38** [comment]
I stopped using this extension several months back. If I encounter the issue again, I'll open a new issue.
