### ISSUE TITLE
Authentification mode not available on SQL Database Output

### ISSUE THREAD

**Issue by helenaf** [microsoft/vscode-asa#56]
I can't select Managed Identity as authentification for SQL Database Output. There is no field for selecting authentification mode as there is for example Data Lake or Power Bi. Username and password is the only way to go.

**Comment by yicw16322** [comment]
Hi helenaf

Which version of extension are you using? Could you please try to use parameter AuthenticationMode to select managed identity as the picture presented below?

thanks

![image](https://user-images.githubusercontent.com/79968220/132271346-207c3475-93b1-4447-9259-8bbaa05dba87.png)

**Comment by helenaf** [comment]
Sorry! Realizing now this is the forum for VS Code and I was using Visual Studio Professional. Switched to VS Code and the option is there, so problem solved for me.

**Comment by yicw16322** [comment]
@helenaf  Np, when you use VS code, any feedbacks are very welcome.
