### ISSUE TITLE
NPM package azure-streamanalytics-cicd broken in Azure DevOps

### ISSUE THREAD

**Issue by kipusoep** [microsoft/vscode-asa#67]
We have an issue where the latest release 2.2.6 has broken our pipeline.
The `azure-streamanalytics-cicd build` command throws an error:
`Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

Reverting to 2.2.5 fixes the issue.

(From: https://github.com/Azure/azure-stream-analytics/issues/122)

**Comment by kipusoep** [comment]
If it works, then it's still a breaking change, while the version bump was just minor.
Is there a reason why the asaproj file isn't supported anymore?

**Comment by pengyuli-ms** [comment]
Sure @kipusoep , this is a regression from 2.2.5 -> 2.2.6, and we will figure out why and release a new version to fix this asap. Thanks for your feedback!

**Comment by kipusoep** [comment]
FYI I don't have a asaproj.json file in my project folder.

**Comment by pengyuli-ms** [comment]
Thanks! We've found the root cause and will release a new version asap.

**Comment by pengyuli-ms** [comment]
Hi @kipusoep , we've released a new version of CICD tool here: [azure-streamanalytics-cicd 2.2.7](https://www.npmjs.com/package/azure-streamanalytics-cicd), it should have this issue fixed, please take a try.

Thanks again for your feedback!

**Comment by kipusoep** [comment]
Yes works, thanks @pengyuli-ms
