### ISSUE TITLE
Input name and column name auto completion not working on Mac and Linux

### ISSUE THREAD

**Issue by su-jie** [microsoft/vscode-asa#7]
Version: 0.1.1

Issue:

When I added a local input or a cloud input, there is no input name and column name auto completion when editing the script. It works on Windows as below. 

![image](https://user-images.githubusercontent.com/24801534/61574194-7bf36d80-aaee-11e9-8a8b-16c1e51786d0.png)

**Comment by ms-guizha** [comment]
fixed issue in preview 0.1.2. you can verify and close this issue

**Comment by authuir** [comment]
Closed as resolved.
