### ISSUE TITLE
[Survey] User feedback

### ISSUE THREAD

**Issue by myintn02** [microsoft/vscode-asa#96]
VSCode Version: 1.77.1,
Extension Version: 1.4.8,
OS: OSX

**1. Overall, how would you rate your experience with the Stream Analytics Visual Studio Code Extension? Please rate us from 1 (poor) to 10 (excellent).**

**2. What do you like or dislike about the Stream Analytics Visual Studio Code Extension?**

**3. What improvements do you suggest for Stream Analytics Visual Studio Code Extension?**

**Comment by myintn02** [comment]
1. 7 Have issue with docker image 
2. good I like it for being user friendly but can be more intuitive 
3. more clear visual understanding with interactive learning pattern for the new user, problem solving help when issues arise

**Comment by ruiminwang** [comment]
What issues are you having when using Azure Stream Analytics extension?
