### ISSUE TITLE
NPM azure-streamanalytics-cicd fails to install

### ISSUE THREAD

**Issue by yfredrix** [microsoft/vscode-asa#97]
- VS Code Version: 
- Extension Version: 3.0.1
- OS Version: 20230417.1 (Devops Runner Image)
---

Steps to Reproduce:

1. npm install -g azure-streamanalytics-cicd
2. azure-streamanalytics-cicd build

This results into an error
```
A JSON parsing exception occurred in [/usr/local/lib/node_modules/azure-streamanalytics-cicd/bin/LocalRunService.deps.json], offset 0 (line 1, column 1): Invalid value.
Error initializing the dependency resolver: An error occurred while parsing: /usr/local/lib/node_modules/azure-streamanalytics-cicd/bin/LocalRunService.deps.json
##[error]Bash exited with code '139'.
```

**Comment by ruiminwang** [comment]
Sorry @yfredrix , we are hotfixing it. Will release the new bits in a day or two.

**Comment by ruiminwang** [comment]
Hi @yfredrix , we have released a hotfix azure-streamanalytics-cicd.3.0.2, could you have a try? Thank you.

**Comment by yfredrix** [comment]
Yes this fixes the issue. Thank you
